### ISSUE TITLE
大佬你这个是激光扫描吗？能不能给个qq咨询一下你

### ISSUE THREAD

**Issue by weizhishu1901** [XuJin186/react-native-pda-scan#1]

**Comment by XuJin186** [comment]
> _没有提供描述。_

是激光扫描

**Comment by weizhishu1901** [comment]
那是直接使用pad激光扫描按钮吗

**Comment by XuJin186** [comment]
是

**Comment by weizhishu1901** [comment]
可以帮忙加一下捷宝的吗？接收数据的广播名："com.android.receive_scan_action”
接收数据的广播中数据字段名：”data”

**Comment by XuJin186** [comment]
你自己fork一份增加吧  我没设备不好处理

**Comment by weizhishu1901** [comment]
const { code, error } = usePdaScan({(code) => {console.log(code)},(error) => {console.log(error)}, "always"});
大神为什么不可以使用啊？有什么不对吗？

**Comment by XuJin186** [comment]
只写了hook版本

**Comment by weizhishu1901** [comment]
大神能帮忙写一下其他版本的吗？不太会写

**Comment by XuJin186** [comment]
我这只是个开源项目  不是咨询公司啊
